services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always # 🔹 Agregado
    ports:
      - "5672:5672" # Puerto para conexión AMQP
      - "15672:15672" # Puerto para la interfaz web de gestión
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    healthcheck: # 🔹 Agregado para verificar si RabbitMQ está listo
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./producer
    container_name: producer
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy # 🔹 Espera hasta que RabbitMQ esté listo
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq
      ROLE: producer # 🔹 Agregado para usar el mismo código en ambos

  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy # 🔹 Espera hasta que RabbitMQ esté listo
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq
      ROLE: consumer # 🔹 Agregado
